services:
  postgres:
    image: postgres:18.1
    restart: unless-stopped
    container_name: Hono-learn-japanese
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=12345
      - POSTGRES_USER=postgres
      - POSTGRES_DB=learn_japanese
